"""empty message

Revision ID: 3d30e6ae5a24
Revises: 
Create Date: 2022-04-10 17:45:08.983114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d30e6ae5a24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('teams', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_class', sa.String(), nullable=False),
    sa.Column('material_subClass', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobsite_id'], ['job_site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jobsite_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storage_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storagetype_id', sa.Integer(), nullable=True),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobsite_id'], ['job_site.id'], ),
    sa.ForeignKeyConstraint(['storagetype_id'], ['storage_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('team_lead', sa.Boolean(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['jobsite_id'], ['job_site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('storage_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['material_class.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tower_number', sa.String(length=5), nullable=False),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.Column('storagelocation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobsite_id'], ['job_site.id'], ),
    sa.ForeignKeyConstraint(['storagelocation_id'], ['storage_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('msds_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mat_id', sa.Integer(), nullable=True),
    sa.Column('msds_link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mat_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tower_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('jobsite_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['jobsite_id'], ['job_site.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tower_id'], ['tower.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.Column('note_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['jobsite_id'], ['job_site.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('join_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['jobsite_id'], ['job_site.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_Team',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('active_participant',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    op.drop_table('active_participant')
    op.drop_table('user_Team')
    op.drop_table('room')
    op.drop_table('join_notification')
    op.drop_table('event')
    op.drop_table('Note')
    op.drop_table('team')
    op.drop_table('msds_info')
    op.drop_table('tower')
    op.drop_table('material')
    op.drop_table('user')
    op.drop_table('storage_location')
    op.drop_table('connex')
    op.drop_table('storage_type')
    op.drop_table('material_class')
    op.drop_table('job_site')
    # ### end Alembic commands ###
