"""empty message

Revision ID: ea3c72cd3cb5
Revises: 
Create Date: 2022-04-01 10:46:22.453871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3c72cd3cb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('teams', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('team_lead', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('connex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobsite_id'], ['job_site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jobsite_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['jobsite_id'], ['job_site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tower_number', sa.String(length=5), nullable=False),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobsite_id'], ['job_site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_site',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['job_site.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'site_id')
    )
    op.create_table('chemical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connex_inventory', sa.Integer(), nullable=True),
    sa.Column('tower_inventory', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['connex_inventory'], ['connex.id'], ),
    sa.ForeignKeyConstraint(['tower_inventory'], ['tower.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connex_inventory', sa.Integer(), nullable=True),
    sa.Column('tower_inventory', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['connex_inventory'], ['connex.id'], ),
    sa.ForeignKeyConstraint(['tower_inventory'], ['tower.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_team',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_team')
    op.drop_table('material')
    op.drop_table('chemical')
    op.drop_table('user_site')
    op.drop_table('tower')
    op.drop_table('team')
    op.drop_table('connex')
    op.drop_table('user')
    op.drop_table('job_site')
    # ### end Alembic commands ###
