"""empty message

Revision ID: eb1488f40a78
Revises: aecc4a09f416
Create Date: 2022-04-04 21:53:31.437093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1488f40a78'
down_revision = 'aecc4a09f416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_type', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_type', sa.Column('name', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
